### PR TITLE
docs: make README.md example easier to grok

### PR DESCRIPTION
**Pull request by asimpson**
Cleaned up the example by removing the need to import `rjsx` and explaining `subscribe` in a bit more detail

### CODE REVIEW

**Review by sd2k — APPROVED** [review]
Nice, thanks!

**Comment by asimpson** [comment]
:+1: Any idea why drone is failing? I can't see the build logs :frowning_face:

**Comment by sd2k** [comment]
Oh, it's spell check, you can run it locally with yarn spellcheck. Weird that you can't see the build logs 😕

**Comment by asimpson** [comment]
Ah thanks! Done and pushed :)

**Pull request merged**
